import { AbsoluteFill } from "remotion";
import catalog from "../capabilities/asset-catalog.json";
import { IconAsset } from "../shape-primitives";
import { colors, typography } from "../theme";

// =========================================================================
// AssetGallery — a catalog-DRIVEN sheet of every <IconAsset> in the library.
//
// It ENUMERATES from src/capabilities/asset-catalog.json (generated by
// `npm run icons:build` — the source of truth for the asset library), so the
// sheet never goes stale: add an asset, rebuild the catalog, and it appears
// here automatically. Nothing about the 89 assets is hardcoded.
//
// Layout: a single tall sheet. Each category is a band with a `Category · count`
// header, then a grid of cells. Each cell renders `<IconAsset name variant=
// "color">` at a clear size with the asset name labelled beneath. Mirrors the
// look of ComponentGallery so the two QC sheets feel consistent.
// =========================================================================

const FONT = typography.fontFamily;

// ---- catalog shape (only the fields we read) ----
type CatalogAsset = {
  name: string;
  category: string;
  desc: string;
};

const ALL_ASSETS = (catalog.assets as CatalogAsset[]) ?? [];

// Per-category accent color, cycling the theme palette. Categories not listed
// fall back to the cycle so new categories still get a color (never stale).
const ACCENT_BY_CATEGORY: Record<string, string> = {
  literacy: colors.coral,
  math: colors.sunshine,
  object: colors.sky,
  symbol: colors.lavender,
  nature: colors.mint,
  celebration: colors.reward,
  tool: colors.sky,
  "character-face": colors.lavender,
  animal: colors.mint,
  generated: colors.coral,
};
const ACCENT_CYCLE = [
  colors.coral,
  colors.sunshine,
  colors.sky,
  colors.lavender,
  colors.mint,
  colors.reward,
];

// Order categories: newest/most-relevant first (literacy = the new ancient
// glyphs, object holds the new stationery batch), then the rest alphabetically.
// Any category present in the catalog but missing from this list still renders
// (appended, alphabetical) — so the sheet auto-grows as the catalog grows.
const PRIORITY_CATEGORIES = ["literacy", "object", "math"];

const orderCategories = (): string[] => {
  const present = Array.from(new Set(ALL_ASSETS.map((a) => a.category)));
  const head = PRIORITY_CATEGORIES.filter((c) => present.includes(c));
  const tail = present
    .filter((c) => !head.includes(c))
    .sort((a, b) => a.localeCompare(b));
  return [...head, ...tail];
};

const accentFor = (category: string, index: number): string =>
  ACCENT_BY_CATEGORY[category] ?? ACCENT_CYCLE[index % ACCENT_CYCLE.length];

// ---- layout constants (mirrors ComponentGallery proportions) ----
const CANVAS_WIDTH = 2600;
const PAD_X = 60;
const COLUMNS = 6;
const COL_GAP = 24;
const CELL_W = (CANVAS_WIDTH - PAD_X * 2 - COL_GAP * (COLUMNS - 1)) / COLUMNS;
const CELL_H = 240;
const ICON_SIZE = 120; // ~110–130px render size for the asset art
const ROW_GAP = 24;
const BAND_HEADER_H = 86;
const BAND_GAP = 36;
const TOP_TITLE_H = 130;

type PlacedCell = {
  name: string;
  x: number;
  y: number;
  w: number;
  h: number;
};

type PlacedBand = {
  label: string;
  accent: string;
  count: number;
  y: number;
  height: number;
};

// Pack each category's assets into COLUMNS columns, row by row, in catalog
// order. Returns placed bands + cells + the derived total sheet height.
const layoutAll = () => {
  const cells: PlacedCell[] = [];
  const bands: PlacedBand[] = [];
  let cursorY = TOP_TITLE_H;

  orderCategories().forEach((category, catIndex) => {
    const entries = ALL_ASSETS.filter((a) => a.category === category);
    const bandTop = cursorY;
    const headerBottom = bandTop + BAND_HEADER_H;
    let rowTop = headerBottom + 12;

    for (let i = 0; i < entries.length; i += COLUMNS) {
      const rowEntries = entries.slice(i, i + COLUMNS);
      rowEntries.forEach((entry, col) => {
        cells.push({
          name: entry.name,
          x: PAD_X + col * (CELL_W + COL_GAP),
          y: rowTop,
          w: CELL_W,
          h: CELL_H,
        });
      });
      rowTop += CELL_H + ROW_GAP;
    }

    const bandHeight = rowTop - bandTop;
    bands.push({
      label: category,
      accent: accentFor(category, catIndex),
      count: entries.length,
      y: bandTop,
      height: bandHeight,
    });
    cursorY = bandTop + bandHeight + BAND_GAP;
  });

  return { bands, cells, totalHeight: cursorY + 40 };
};

const Cell = ({ cell }: { cell: PlacedCell }) => {
  const centerX = cell.x + cell.w / 2;
  // Icon sits in the upper portion; the name label below it.
  const iconCenterY = cell.y + cell.h / 2 - 12;
  const labelY = cell.y + cell.h - 22;

  return (
    <g>
      <rect
        fill={colors.white}
        height={cell.h}
        rx={18}
        stroke="#E3E8F0"
        strokeWidth={2}
        width={cell.w}
        x={cell.x}
        y={cell.y}
      />
      <g transform={`translate(${centerX} ${iconCenterY})`}>
        <IconAsset name={cell.name} variant="color" width={ICON_SIZE} />
      </g>
      <text
        dominantBaseline="middle"
        fill={colors.textNavy}
        fontFamily={FONT}
        fontSize={19}
        fontWeight={800}
        textAnchor="middle"
        x={centerX}
        y={labelY}
      >
        {cell.name}
      </text>
    </g>
  );
};

const Band = ({ band }: { band: PlacedBand }) => (
  <g>
    <rect
      fill={band.accent}
      height={56}
      opacity={0.22}
      rx={14}
      width={CANVAS_WIDTH - PAD_X * 2}
      x={PAD_X}
      y={band.y}
    />
    <rect
      fill={band.accent}
      height={56}
      rx={8}
      width={14}
      x={PAD_X + 12}
      y={band.y}
    />
    <text
      dominantBaseline="middle"
      fill={colors.textNavy}
      fontFamily={FONT}
      fontSize={36}
      fontWeight={900}
      x={PAD_X + 42}
      y={band.y + 30}
    >
      {`${band.label}  ·  ${band.count}`}
    </text>
  </g>
);

export const AssetGallery: React.FC = () => {
  const { bands, cells, totalHeight } = layoutAll();

  return (
    <AbsoluteFill style={{ backgroundColor: colors.cream }}>
      <svg
        height={totalHeight}
        viewBox={`0 0 ${CANVAS_WIDTH} ${totalHeight}`}
        width={CANVAS_WIDTH}
      >
        <text
          fill={colors.textNavy}
          fontFamily={FONT}
          fontSize={56}
          fontWeight={900}
          x={PAD_X}
          y={72}
        >
          Asset Gallery — catalog-driven IconAsset sheet
        </text>
        <text
          fill={colors.softGrayBlue}
          fontFamily={FONT}
          fontSize={26}
          fontWeight={800}
          x={PAD_X}
          y={108}
        >
          {`${cells.length} assets from asset-catalog.json · ${bands.length} categories · variant="color"`}
        </text>
        {bands.map((band) => (
          <Band band={band} key={band.label} />
        ))}
        {cells.map((cell) => (
          <Cell cell={cell} key={cell.name} />
        ))}
      </svg>
    </AbsoluteFill>
  );
};

// Static sheet — no animation, so any frame is identical. Short duration.
export const assetGalleryDuration = 60;

// Composition canvas size — must equal the SVG so nothing clips. Width is fixed;
// height is derived from the same layout pass the component uses.
export const ASSET_GALLERY_WIDTH = CANVAS_WIDTH;
export const ASSET_GALLERY_HEIGHT = Math.ceil(layoutAll().totalHeight);
