import { colors } from "../theme";
import { ICON_ASSETS, type IconAssetName } from "./iconAssetData";
import {
  PlacedGroup,
  resolveColor,
  type PlacementProps,
  type PrimitiveGroupProps,
  type ThemeColor,
} from "./shared";

export type IconAssetVariant = "color" | "mono";

export type IconAssetProps = PrimitiveGroupProps &
  PlacementProps & {
    /** Asset key — a name present in ICON_ASSETS (generated by
     *  `npm run icons:build` from public/icons/<name>.svg). */
    name: IconAssetName | (string & {});
    /** `"color"` (default) renders the full flat-papercraft fills; its
     *  `var(--icon-*, #hex)` fallbacks already equal the theme hexes, so it is
     *  on-palette with no tint. `"mono"` renders a single-color silhouette via
     *  `currentColor`, driven by `tint`. */
    variant?: IconAssetVariant;
    /** Theme color (or raw CSS color) for the mono variant, set on `color`.
     *  Defaults to textNavy. Ignored by `variant="color"` unless you want to
     *  recolor a specific `--icon-*` swatch (pass that var via `tintVars`). */
    tint?: ThemeColor;
    /** Optional per-swatch overrides for the color variant, keyed by the CSS
     *  var name WITHOUT the `--` prefix (e.g. `{ "icon-coral": "mint" }`).
     *  Each value is theme-resolved. Use to recolor one part of a color asset
     *  to a theme token without editing the traced markup. */
    tintVars?: Record<string, ThemeColor>;
    /** Rendered width in local SVG units. If only one of width/height is given
     *  the other follows the asset's intrinsic aspect ratio. Defaults derive
     *  from `scale` × the asset's viewBox size. */
    width?: number;
    height?: number;
    /** Uniform scale applied to the asset's intrinsic viewBox size when neither
     *  width nor height is given. Default 1 (renders at viewBox size). */
    scale?: number;
  };

const parseViewBox = (viewBox: string): { w: number; h: number } => {
  const parts = viewBox.trim().split(/\s+/).map(Number);
  const w = parts[2];
  const h = parts[3];
  return {
    w: Number.isFinite(w) && w > 0 ? w : 512,
    h: Number.isFinite(h) && h > 0 ? h : 512,
  };
};

// =========================================================================
// IconAsset — render a GENERATED + TRACED flat SVG asset as a placeable,
// scalable, theme-tintable primitive.
//
// This is the "generate → trace → compose" track for fixed-form
// representational objects (a roped stick bundle, a mascot, a prop) that are
// too organic to hand-code well. The traced markup lives in iconAssetData.ts
// (built from public/icons/*.svg by `npm run icons:build`); this component is
// the lesson-agnostic, prop-driven renderer.
//
// Inline approach: the inner markup is injected via dangerouslySetInnerHTML
// inside an <svg viewBox=...> that IconAsset sizes and centers. Inlining is
// required for theme-tinting — an <img src> cannot expose the asset's
// `var(--icon-*)` fills. Because the markup is STATIC build-time data (no
// fetch, no time, no random), the same composition frame renders identically.
//
// Lesson-agnostic: it knows no topic; the caller passes the asset `name`,
// placement, size, and (for recoloring) theme tokens. Deterministic.
// =========================================================================
export const IconAsset = ({
  name,
  variant = "color",
  tint,
  tintVars,
  width,
  height,
  scale = 1,
  transform,
  x = 0,
  y = 0,
  ...groupProps
}: IconAssetProps) => {
  const asset = ICON_ASSETS[name];
  if (!asset) {
    return null;
  }

  const { w: vbW, h: vbH } = parseViewBox(asset.viewBox);

  // Resolve render size: explicit width/height win (a single one preserves the
  // intrinsic aspect ratio); otherwise scale the intrinsic viewBox size.
  let renderW: number;
  let renderH: number;
  if (width != null && height != null) {
    renderW = width;
    renderH = height;
  } else if (width != null) {
    renderW = width;
    renderH = width * (vbH / vbW);
  } else if (height != null) {
    renderH = height;
    renderW = height * (vbW / vbH);
  } else {
    renderW = vbW * scale;
    renderH = vbH * scale;
  }

  const markup = variant === "mono" ? asset.mono : asset.color;

  // For mono, `color` drives `currentColor`. For color, optionally bind named
  // `--icon-*` CSS vars to theme tokens (recolor without retracing).
  const style: React.CSSProperties = {};
  if (variant === "mono") {
    style.color = resolveColor(tint, colors.textNavy);
  } else if (tint) {
    style.color = resolveColor(tint, colors.textNavy);
  }
  if (tintVars) {
    for (const [key, value] of Object.entries(tintVars)) {
      (style as Record<string, string>)[`--${key}`] = resolveColor(
        value,
        colors.textNavy,
      );
    }
  }

  return (
    <PlacedGroup {...groupProps} transform={transform} x={x} y={y}>
      {/* Centered on the local origin so placement props position the asset's
          center, matching the other shape primitives. A nested <svg> with its
          own viewBox scales the traced paths to renderW × renderH. */}
      <g transform={`translate(${-renderW / 2} ${-renderH / 2})`}>
        <svg
          height={renderH}
          style={Object.keys(style).length ? style : undefined}
          viewBox={asset.viewBox}
          width={renderW}
          dangerouslySetInnerHTML={{ __html: markup }}
        />
      </g>
    </PlacedGroup>
  );
};
