import { AbsoluteFill } from "remotion";
import registry from "../capabilities/primitive-registry.json";
import recency from "../capabilities/recency.json";
import { FXDefs } from "../fx";
import { colors, typography } from "../theme";
import { demoProps } from "./demoProps";

// =========================================================================
// ComponentGallery — a registry-DRIVEN gallery of every reusable component.
//
// It ENUMERATES from src/capabilities/primitive-registry.json (the source of
// truth) in family order — counting → literacy → interaction → sketch →
// motion → fx — so any future primitive auto-appears here. The registry stores
// only the component NAME (a string); the React prop VALUES live in
// `demoProps.ts`, looked up by `id`. A registry id with no demo entry renders a
// red "UNMAPPED: <id>" cell, so the gallery dogfoods its own completeness.
//
// Layout: a single tall sheet. A "Recently added / changed" band sits at the
// very top (the N newest components by git recency), then each family is a band
// with a header and a grid of cells (one per component id). Cells are ≥ ~330px
// wide so glyph + variant strip + label stay legible at real render size.
//
// Recency is git-sourced (src/capabilities/recency.json, generated by
// `npm run registry:recency` inside the registry:build chain) so the "newest"
// band and the per-cell date chips AUTO-UPDATE — no manual upkeep, no hardcoded
// component list.
// =========================================================================

const FONT = typography.fontFamily;

// ---- registry shape (only the fields we read) ----
type RegistryEntry = {
  kind?: string;
  id: string;
  component: string;
  status?: string;
  supersededBy?: string;
};

// Deprecated entries are QUARANTINED: excluded from their family band AND the
// recency band, and collected into a single greyed "Legacy / deprecated" band at
// the very bottom. They keep their demoProps demo (the gallery gate stays happy)
// — they just live in the legacy band, dimmed, with a "→ <supersededBy>" pointer.
const isDeprecated = (e: RegistryEntry): boolean => e.status === "deprecated";
const supersededByOf = (id: string): string =>
  allRegistryEntries().find((e) => e.id === id)?.supersededBy ?? "";

const familyOrder = [
  { key: "counting", label: "Counting & number", accent: colors.sunshine },
  { key: "literacy", label: "Literacy & pinyin", accent: colors.coral },
  { key: "interaction", label: "Interaction & sorting", accent: colors.sky },
  { key: "sketch", label: "Sketch / teacher marks", accent: colors.lavender },
  { key: "asset", label: "Generated assets (traced flat SVG)", accent: colors.reward },
  { key: "motion", label: "Motion components", accent: colors.mint },
  { key: "fx", label: "FX components", accent: colors.reward },
] as const;

type FamilyKey = (typeof familyOrder)[number]["key"];

// Group registry entries into the six families, preserving registry order.
// Deprecated entries are EXCLUDED here (they render only in the bottom legacy band).
const collectFamily = (key: FamilyKey): RegistryEntry[] => {
  if (key === "motion") {
    return ((registry.motionComponents as RegistryEntry[]) ?? []).filter(
      (e) => !isDeprecated(e),
    );
  }
  if (key === "fx") {
    return ((registry.fxComponents as RegistryEntry[]) ?? []).filter(
      (e) => !isDeprecated(e),
    );
  }
  return ((registry.primitives as RegistryEntry[]) ?? []).filter(
    (p) => p.kind === key && !isDeprecated(p),
  );
};

// Every deprecated entry across all tiers — the bottom "Legacy / deprecated" band.
const deprecatedEntries = (): RegistryEntry[] =>
  allRegistryEntries().filter(isDeprecated);

// ---- recency (git-sourced, src/capabilities/recency.json) ----
type Recency = Record<string, { ts: number; iso: string }>;
const recencyMap = recency as Recency;
const isoFor = (id: string): string => recencyMap[id]?.iso ?? "";

// The N newest component ids across ALL families, by commit/edit time desc.
// Drives the top "Recently added / changed" band; no hardcoded list.
const RECENT_COUNT = 8;
const allRegistryEntries = (): RegistryEntry[] => [
  ...((registry.primitives as RegistryEntry[]) ?? []),
  ...((registry.motionComponents as RegistryEntry[]) ?? []),
  ...((registry.fxComponents as RegistryEntry[]) ?? []),
];
const recentEntries = (): RegistryEntry[] =>
  allRegistryEntries()
    .filter((e) => recencyMap[e.id] && !isDeprecated(e))
    .sort(
      (a, b) =>
        (recencyMap[b.id]?.ts ?? 0) - (recencyMap[a.id]?.ts ?? 0) ||
        a.id.localeCompare(b.id),
    )
    .slice(0, RECENT_COUNT);

// ---- layout constants ----
const CANVAS_WIDTH = 2600;
const PAD_X = 60;
const COLUMNS = 3;
const COL_GAP = 30;
const CELL_W = (CANVAS_WIDTH - PAD_X * 2 - COL_GAP * (COLUMNS - 1)) / COLUMNS;
const CELL_H_NORMAL = 220;
const CELL_H_TALL = 320;
const ROW_GAP = 28;
const BAND_HEADER_H = 86;
const BAND_GAP = 36;
const TOP_TITLE_H = 130;

type PlacedCell = {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  mapped: boolean;
  legacy?: boolean;
};

type PlacedBand = {
  label: string;
  accent: string;
  count: number;
  y: number;
  height: number;
};

// Pack one band's entries into COLUMNS columns, row by row, starting at
// `bandTop`. A row's height is the max cell height in that row (tall cells bump
// their whole row). Pushes into the shared cells/bands arrays and returns the
// y at which the NEXT band should start. Shared by the recent band + families.
const packBand = (
  label: string,
  accent: string,
  entries: RegistryEntry[],
  bandTop: number,
  cells: PlacedCell[],
  bands: PlacedBand[],
  legacy = false,
): number => {
  const headerBottom = bandTop + BAND_HEADER_H;
  let rowTop = headerBottom + 12;

  for (let i = 0; i < entries.length; i += COLUMNS) {
    const rowEntries = entries.slice(i, i + COLUMNS);
    const rowHeight = rowEntries.some((e) => demoProps[e.id]?.tall)
      ? CELL_H_TALL
      : CELL_H_NORMAL;

    rowEntries.forEach((entry, col) => {
      cells.push({
        id: entry.id,
        x: PAD_X + col * (CELL_W + COL_GAP),
        y: rowTop,
        w: CELL_W,
        h: rowHeight,
        mapped: Boolean(demoProps[entry.id]),
        legacy,
      });
    });
    rowTop += rowHeight + ROW_GAP;
  }

  const bandHeight = rowTop - bandTop;
  bands.push({
    label,
    accent,
    count: entries.length,
    y: bandTop,
    height: bandHeight,
  });
  return bandTop + bandHeight + BAND_GAP;
};

const layoutAll = () => {
  const cells: PlacedCell[] = [];
  const bands: PlacedBand[] = [];
  let cursorY = TOP_TITLE_H;

  // Top band: the N newest components by git recency. Cells here REUSE the same
  // ids as the family bands below (same renderer, same demoProps lookup), so a
  // recent component shows twice — once in this discovery band, once in its
  // family. An unmapped recent id still renders its UNMAPPED state.
  const recent = recentEntries();
  if (recent.length) {
    cursorY = packBand(
      "Recently added / changed",
      colors.reward,
      recent,
      cursorY,
      cells,
      bands,
    );
  }

  for (const fam of familyOrder) {
    cursorY = packBand(
      `${fam.label}`,
      fam.accent,
      collectFamily(fam.key),
      cursorY,
      cells,
      bands,
    );
  }

  // Bottom band: superseded capabilities, greyed. They are excluded from every
  // family + the recency band above and quarantined here, each with a
  // "→ <supersededBy>" pointer rendered in the cell.
  const legacy = deprecatedEntries();
  if (legacy.length) {
    cursorY = packBand(
      "Legacy / deprecated",
      colors.softGrayBlue,
      legacy,
      cursorY,
      cells,
      bands,
      true,
    );
  }

  return { bands, cells, totalHeight: cursorY + 40 };
};

// Small date chip (the iso recency day) in the top-right corner of a cell, so
// recency is visible on EVERY cell (recent band + family bands). Width tracks
// the glyph count of "YYYY-MM-DD".
const DateChip = ({ cell }: { cell: PlacedCell }) => {
  const iso = isoFor(cell.id);
  if (!iso) return null;
  const chipW = 108;
  const chipH = 28;
  const chipX = cell.x + cell.w - chipW - 14;
  const chipY = cell.y + 14;
  return (
    <g>
      <rect
        fill={colors.cream}
        height={chipH}
        rx={9}
        stroke="#E3E8F0"
        strokeWidth={1.5}
        width={chipW}
        x={chipX}
        y={chipY}
      />
      <text
        dominantBaseline="middle"
        fill={colors.softGrayBlue}
        fontFamily={FONT}
        fontSize={17}
        fontWeight={800}
        textAnchor="middle"
        x={chipX + chipW / 2}
        y={chipY + chipH / 2 + 1}
      >
        {iso}
      </text>
    </g>
  );
};

const Cell = ({ cell }: { cell: PlacedCell }) => {
  const demo = demoProps[cell.id];
  const centerX = cell.x + cell.w / 2;
  const centerY = cell.y + cell.h / 2 + 8; // a touch low to leave room for label
  // Legacy cells are dimmed (grey surface, faded demo) and carry a
  // "→ <supersededBy>" pointer to the sanctioned replacement.
  const replacement = cell.legacy ? supersededByOf(cell.id) : "";

  return (
    <g opacity={cell.legacy ? 0.55 : 1}>
      <rect
        fill={cell.legacy ? colors.cream : cell.mapped ? colors.white : "#FFE2E2"}
        height={cell.h}
        rx={18}
        stroke={cell.legacy ? colors.softGrayBlue : cell.mapped ? "#E3E8F0" : colors.coral}
        strokeDasharray={cell.legacy ? "10 8" : undefined}
        strokeWidth={cell.legacy ? 2.5 : cell.mapped ? 2 : 4}
        width={cell.w}
        x={cell.x}
        y={cell.y}
      />
      {/* id label, top-left of cell */}
      <text
        fill={cell.legacy ? colors.softGrayBlue : cell.mapped ? colors.textNavy : colors.coral}
        fontFamily={FONT}
        fontSize={22}
        fontWeight={900}
        x={cell.x + 18}
        y={cell.y + 32}
      >
        {cell.id}
      </text>
      {/* "→ <supersededBy>" replacement pointer (legacy cells only), top-left under the id */}
      {cell.legacy && replacement ? (
        <text
          fill={colors.softGrayBlue}
          fontFamily={FONT}
          fontSize={18}
          fontWeight={800}
          x={cell.x + 18}
          y={cell.y + 56}
        >
          {`→ ${replacement}`}
        </text>
      ) : null}
      <DateChip cell={cell} />
      {cell.mapped ? (
        <g transform={`translate(${centerX} ${centerY})`}>{demo.render()}</g>
      ) : (
        <text
          dominantBaseline="middle"
          fill={colors.coral}
          fontFamily={FONT}
          fontSize={30}
          fontWeight={900}
          textAnchor="middle"
          x={centerX}
          y={centerY}
        >
          {`UNMAPPED: ${cell.id}`}
        </text>
      )}
    </g>
  );
};

const Band = ({ band }: { band: PlacedBand }) => (
  <g>
    <rect
      fill={band.accent}
      height={56}
      opacity={0.22}
      rx={14}
      width={CANVAS_WIDTH - PAD_X * 2}
      x={PAD_X}
      y={band.y}
    />
    <rect
      fill={band.accent}
      height={56}
      rx={8}
      width={14}
      x={PAD_X + 12}
      y={band.y}
    />
    <text
      dominantBaseline="middle"
      fill={colors.textNavy}
      fontFamily={FONT}
      fontSize={36}
      fontWeight={900}
      x={PAD_X + 42}
      y={band.y + 30}
    >
      {`${band.label}  ·  ${band.count}`}
    </text>
  </g>
);

export const ComponentGallery: React.FC = () => {
  const { bands, cells, totalHeight } = layoutAll();
  // Count UNIQUE registry components (not placed cells): recent cells reuse
  // family ids, so cells over-counts by the size of the recent band.
  const uniqueIds = new Set(cells.map((c) => c.id));
  const componentCount = uniqueIds.size;
  const mappedCount = [...uniqueIds].filter((id) => Boolean(demoProps[id]))
    .length;

  return (
    <AbsoluteFill style={{ backgroundColor: colors.cream }}>
      <svg
        height={totalHeight}
        viewBox={`0 0 ${CANVAS_WIDTH} ${totalHeight}`}
        width={CANVAS_WIDTH}
      >
        <FXDefs />
        <text
          fill={colors.textNavy}
          fontFamily={FONT}
          fontSize={56}
          fontWeight={900}
          x={PAD_X}
          y={72}
        >
          Component Gallery — registry-driven QC sheet
        </text>
        <text
          fill={colors.softGrayBlue}
          fontFamily={FONT}
          fontSize={26}
          fontWeight={800}
          x={PAD_X}
          y={108}
        >
          {`${componentCount} components from primitive-registry.json · ${mappedCount} mapped · ${componentCount - mappedCount} unmapped · newest first up top`}
        </text>
        {bands.map((band) => (
          <Band band={band} key={band.label} />
        ))}
        {cells.map((cell) => (
          <Cell cell={cell} key={`${cell.y}-${cell.x}-${cell.id}`} />
        ))}
      </svg>
    </AbsoluteFill>
  );
};

// The gallery still frame: high enough that frame-driven motion/fx (PopIn,
// PulseCircle, Smear, SparkleBurst, GlintFlash, GlowPulse, ShineSweep, Sparkle,
// Breathe, FollowPath/DrawPath/Drag chains) are visibly mid/!-effect, but low
// enough that one-shot bursts have not yet faded out.
export const COMPONENT_GALLERY_STILL_FRAME = 22;
export const componentGalleryDuration = 90;

// Composition canvas size — must equal the SVG so nothing clips. Width is fixed;
// height is derived from the same layout pass the component uses.
export const COMPONENT_GALLERY_WIDTH = CANVAS_WIDTH;
export const COMPONENT_GALLERY_HEIGHT = Math.ceil(layoutAll().totalHeight);
