// kptest-greetings-verify — reconciled cue timeline (Wave 3.5, orchestrator-
// owned, mechanical). v4 CUE-ANCHORED AUDIO.
//
// THE CUE IS THE UNIT OF COORDINATION — and in v4 that is true for AUDIO too.
// Each cue owns a MEASURED audio clip anchored to its own window (see
// `kptestGreetingsVerifyVoiceClips`, mounted one `<Sequence from={fromFrame}>`
// each by the AudioLayer). A clip can NEVER cross a cue boundary, so the
// continuous-WAV drift class (docs/pipeline-architecture.md §6) is structurally
// impossible. There is NO ASR boundary correction, NO detected-silence snapping,
// NO PADDED_CUE_DURATIONS_FRAMES — the reconcile just chains the clip lengths:
//
//   cueFrames = max(narrationFrames + gapFrames, motionFrames) + tail
//
// Inputs (read, never hand-copied):
//   - src/lessons/generated/kptestGreetingsVerifyClips.ts  (the AUDIO TRUTH:
//       per-cue trimmed clip + exact narrationFrames + typed gap — generated by
//       Wave 3a voice)
//   - lesson-data/kptest-greetings-verify/visual-design.md §4 (per-cue motion
//       budget)
//
// CAPTIONS ride the reconciled windows verbatim (Wave 2b plan = spoken narration
// per cue). TAIL = 9 frames (0.3s) breathing room.

import {
  cueToCaption,
  reconcileClipTimeline,
  type CaptionCue,
  type VoiceClip,
} from "@studio/narration-kit";

import { kptestGreetingsVerifyClips } from "./generated/kptestGreetingsVerifyClips";

const FPS = 30;
const TAIL_FRAMES = 9;

// Per-cue visual motion budget (seconds) from
// lesson-data/kptest-greetings-verify/visual-design.md §4 Visual Contract. The
// MINIMUM time each cue's motion needs to read for an 8-year-old. The visual
// design authors one "recap" entry at 13.0s; the Wave 2b plan splits it into
// recap-1 (7.5s) + recap-2 (5.5s) for maxClipSeconds. 7.5 + 5.5 = 13.0 ✓.
const VISUAL_MOTION_SECONDS: Record<string, number> = {
  "topic-intro": 2.5,
  greet: 4.0,
  "im-slow-model": 9.0,
  "im-choral-echo": 7.0,
  "im-learner-gap": 5.0,
  farewell: 4.5,
  "recap-1": 7.5,
  "recap-2": 5.5,
};

const reconciled = reconcileClipTimeline({
  clips: kptestGreetingsVerifyClips,
  visualBudgets: VISUAL_MOTION_SECONDS,
  fps: FPS,
  tailFrames: TAIL_FRAMES,
});

// Reconciled cue list — the single source of truth for visuals, captions, audio.
export const kptestGreetingsVerifyCues = reconciled.cues;

// Total composition length = the last reconciled cue's endFrame.
export const kptestGreetingsVerifyDuration: number = reconciled.durationFrames;

// Per-cue voice clips, each anchored to its cue window. Consumed by
// LessonAudioLayer (one Sequence per clip) and to derive the bed-duck windows.
export const kptestGreetingsVerifyVoiceClips: VoiceClip[] =
  reconciled.voiceClips;

// Caption cues derived from the SAME reconciled windows — captions cannot drift
// from visuals because they read this timeline.
export const kptestGreetingsVerifyLessonCaptionCues: CaptionCue[] =
  reconciled.cues.map(cueToCaption);
