// W3.5 cue-anchored reconcile for kptest-first-second-third.
// Generated by the W3.5 node — DO NOT EDIT BY HAND.
// Re-run this node to regenerate after any voice or visual-design change.

import {
  cueToCaption,
  reconcileClipTimeline,
  type CaptionCue,
  type VoiceClip,
} from "@studio/narration-kit";
import { kptestFirstSecondThirdClips } from "./generated/kptestFirstSecondThirdClips";

const FPS = 30;
const TAIL_FRAMES = 9;

// One entry per cue id in kptestFirstSecondThirdClips.
// Values from visual-design.md §3 per-cue motion budget table.
const VISUAL_MOTION_SECONDS: Record<string, number> = {
  "intro": 3.0,
  "arrive-first": 4.0,
  "name-first": 3.0,
  "arrive-second": 3.5,
  "count-second": 6.0,
  "arrive-third": 3.5,
  "count-third": 8.0,
  "ask-second": 2.0,
  "reveal-second": 4.5,
  "ask-third": 2.0,
  "reveal-third": 4.0,
  "recap-invite": 2.0,
  "recap-count": 9.0,
};

const reconciled = reconcileClipTimeline({
  clips: kptestFirstSecondThirdClips,
  visualBudgets: VISUAL_MOTION_SECONDS,
  fps: FPS,
  tailFrames: TAIL_FRAMES,
});

export const kptestFirstSecondThirdCues = reconciled.cues;
export const kptestFirstSecondThirdDuration: number = reconciled.durationFrames;
export const kptestFirstSecondThirdVoiceClips: VoiceClip[] = reconciled.voiceClips;
export const kptestFirstSecondThirdLessonCaptionCues: CaptionCue[] =
  reconciled.cues.map(cueToCaption);
