// kptest-fenyuhe-six — reconciled cue timeline (Wave 3.5, orchestrator-owned,
// mechanical). v4 CUE-ANCHORED AUDIO.
//
// THE CUE IS THE UNIT OF COORDINATION — and in v4 that is true for AUDIO too.
// Each cue owns a MEASURED audio clip anchored to its own window (see
// `kptestFenyuheSixVoiceClips`, mounted one `<Sequence from={fromFrame}>`
// each by the AudioLayer). A clip can NEVER cross a cue boundary, so the
// continuous-WAV drift class (docs/pipeline-architecture.md §6) is structurally
// impossible. There is NO ASR boundary correction, NO detected-silence snapping,
// NO PADDED_CUE_DURATIONS_FRAMES — the reconcile just chains the clip lengths:
//
//   cueFrames = max(narrationFrames + gapFrames, motionFrames) + tail
//
// Inputs (read, never hand-copied):
//   - src/lessons/generated/kptestFenyuheSixClips.ts  (the AUDIO TRUTH:
//       per-cue trimmed clip + exact narrationFrames + typed gap — generated by
//       Wave 3a voice; accepted frozen at 9/9 cues per
//       lesson-data/kptest-fenyuhe-six/_logs/w3a-voice-asr.md)
//   - lesson-data/kptest-fenyuhe-six/visual-design.md §2 (per-cue motion budget
//       in seconds)
//
// CAPTIONS ride the reconciled windows verbatim (Wave 2b plan = spoken narration
// per cue). TAIL = 9 frames (0.3s) breathing room.

import {
  cueToCaption,
  reconcileClipTimeline,
  type CaptionCue,
  type VoiceClip,
} from "@studio/narration-kit";

import { kptestFenyuheSixClips } from "./generated/kptestFenyuheSixClips";

const FPS = 30;
const TAIL_FRAMES = 9;

// Per-cue visual motion budget (seconds) from
// lesson-data/kptest-fenyuhe-six/visual-design.md §2 "Per-cue visualMotionSeconds".
// The MINIMUM time each cue's motion needs to read for a 6-year-old; the
// reconcile picks `max(narration + gap, motion) + tail` per cue.
const VISUAL_MOTION_SECONDS: Record<string, number> = {
  "cue-announce-split-1of5": 6.5,
  "cue-conserve-1of5": 4.5,
  "cue-split-2of4": 4.5,
  "cue-conserve-2of4": 4.5,
  "cue-split-3of3": 5.0,
  "cue-conserve-3of3": 4.5,
  "cue-learner-response-gap": 5.0,
  "cue-reveal-answer": 3.5,
  "cue-spaced-recap-all-three": 6.5,
};

const reconciled = reconcileClipTimeline({
  clips: kptestFenyuheSixClips,
  visualBudgets: VISUAL_MOTION_SECONDS,
  fps: FPS,
  tailFrames: TAIL_FRAMES,
});

// Reconciled cue list — the single source of truth for visuals, captions, audio.
export const kptestFenyuheSixCues = reconciled.cues;

// Total composition length = the last reconciled cue's endFrame.
export const kptestFenyuheSixDuration: number = reconciled.durationFrames;

// Per-cue voice clips, each anchored to its cue window. Consumed by
// LessonAudioLayer (one Sequence per clip) and to derive the bed-duck windows.
export const kptestFenyuheSixVoiceClips: VoiceClip[] = reconciled.voiceClips;

// Caption cues derived from the SAME reconciled windows — captions cannot drift
// from visuals because they read this timeline.
export const kptestFenyuheSixLessonCaptionCues: CaptionCue[] =
  reconciled.cues.map(cueToCaption);
