import "./index.css";
import { Composition } from "remotion";
import {
  ComponentGallery,
  COMPONENT_GALLERY_HEIGHT,
  COMPONENT_GALLERY_WIDTH,
  componentGalleryDuration,
} from "./component-gallery/ComponentGallery";
import {
  ABSTRACTION_LADDER_DEMO_DURATION,
  AbstractionLadderColumn,
  AbstractionLadderRow,
} from "./scenes/AbstractionLadderDemo";
import {
  COUNTING_BEAD_HARDEST_DURATION,
  COUNTING_BEAD_MULTIPLICITY_DURATION,
  CountingBeadDeviceHardest,
  CountingBeadDeviceMultiplicity,
} from "./scenes/CountingBeadDeviceDemo";
import { InkWashDemo } from "./scenes/InkWashDemo";
import {
  AssetMorphDemo,
  ASSET_MORPH_DEMO_DURATION,
} from "./scenes/AssetMorphDemo";
import {
  GLYPH_HARDEST_DURATION,
  GLYPH_MULTIPLICITY_DURATION,
  GLYPH_SYMBOLS_DURATION,
  GlyphStrokeWriterHardest,
  GlyphStrokeWriterMultiplicity,
  GlyphStrokeWriterSymbols,
} from "./scenes/GlyphStrokeWriterDemo";
import {
  ORDERED_ROW_SPOTLIGHT_DEMO_DURATION,
  OrderedRowSpotlightFlip,
  OrderedRowSpotlightMultiplicity,
  OrderedRowSpotlightSplit,
} from "./scenes/OrderedRowSpotlightDemo";
import {
  ORDINAL_LABEL_TOKEN_DEMO_DURATION,
  OrdinalLabelTokenHardest,
  OrdinalLabelTokenMultiplicity,
} from "./scenes/OrdinalLabelTokenDemo";
import {
  CountingDemo,
  CompleteComparisonLesson,
  CompleteFenYuHeLesson,
  CompleteKp1FenYuHeIntroLesson,
  CompleteKp2CountingByTensLesson,
  CompleteKp2v2CountingByTensLesson,
  CompleteMakeTenLesson,
  CompletePinyinToneLesson,
  CompleteTenOnesMakeOneTenLesson,
  EducationShapeShowcase,
  FishCountingLesson,
  HanziMatchLesson,
  HybridSketchMotionDemo,
  MyComposition,
  OneToOneCompareLesson,
  PathFollowDemo,
  PinyinToneLesson,
  PrimitiveCheckKp1FenHeDiagramHardest,
  PrimitiveCheckKp1FenHeDiagramMigration,
  PrimitiveCheckKp1FenHeDiagramMultiplicity,
  PrimitiveCheckTenOnesMakeOneTenBundleWrap,
  PrimitiveCheckTenOnesMakeOneTenStickRow,
  ShapePrimitiveGallery,
  StrokeTraceDemo,
  primitiveCheckKp1FenHeDuration,
  primitiveCheckTenOnesMakeOneTenDuration,
  completeComparisonLessonDefaultProps,
  completeComparisonLessonDuration,
  completeFenYuHeLessonDefaultProps,
  completeFenYuHeLessonDuration,
  completeKp1FenYuHeIntroLessonDefaultProps,
  completeKp1FenYuHeIntroLessonDuration,
  completeKp2CountingByTensLessonDefaultProps,
  completeKp2CountingByTensLessonDuration,
  completeKp2v2CountingByTensLessonDefaultProps,
  completeKp2v2CountingByTensLessonDuration,
  completeMakeTenLessonDefaultProps,
  completeMakeTenLessonDuration,
  completePinyinToneLessonDefaultProps,
  completePinyinToneLessonDuration,
  completeTenOnesMakeOneTenLessonDefaultProps,
  completeTenOnesMakeOneTenLessonDuration,
  educationSceneDuration,
  educationShowcaseDuration,
  hybridSketchMotionDuration,
} from "./Composition";
import { video } from "./theme";

const compositionDefaults = {
  fps: video.fps,
  height: video.height,
  width: video.width,
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="SvgPrimitiveShowcase"
        component={MyComposition}
        durationInFrames={video.showcaseDuration}
        {...compositionDefaults}
      />
      <Composition
        id="CountingDemo"
        component={CountingDemo}
        durationInFrames={video.sceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PathFollowDemo"
        component={PathFollowDemo}
        durationInFrames={video.sceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="AbstractionLadderRow"
        component={AbstractionLadderRow}
        durationInFrames={ABSTRACTION_LADDER_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="AbstractionLadderColumn"
        component={AbstractionLadderColumn}
        durationInFrames={ABSTRACTION_LADDER_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="CountingBeadDeviceHardest"
        component={CountingBeadDeviceHardest}
        durationInFrames={COUNTING_BEAD_HARDEST_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="CountingBeadDeviceMultiplicity"
        component={CountingBeadDeviceMultiplicity}
        durationInFrames={COUNTING_BEAD_MULTIPLICITY_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="StrokeTraceDemo"
        component={StrokeTraceDemo}
        durationInFrames={video.sceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="HybridSketchMotionDemo"
        component={HybridSketchMotionDemo}
        durationInFrames={hybridSketchMotionDuration}
        {...compositionDefaults}
      />
      <Composition
        id="EducationShapeShowcase"
        component={EducationShapeShowcase}
        durationInFrames={educationShowcaseDuration}
        {...compositionDefaults}
      />
      <Composition
        id="ShapePrimitiveGallery"
        component={ShapePrimitiveGallery}
        durationInFrames={educationSceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="FishCountingLesson"
        component={FishCountingLesson}
        durationInFrames={educationSceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="OneToOneCompareLesson"
        component={OneToOneCompareLesson}
        durationInFrames={educationSceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteComparisonLesson"
        component={CompleteComparisonLesson}
        durationInFrames={completeComparisonLessonDuration}
        defaultProps={completeComparisonLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteFenYuHeLesson"
        component={CompleteFenYuHeLesson}
        durationInFrames={completeFenYuHeLessonDuration}
        defaultProps={completeFenYuHeLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteMakeTenLesson"
        component={CompleteMakeTenLesson}
        durationInFrames={completeMakeTenLessonDuration}
        defaultProps={completeMakeTenLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompletePinyinToneLesson"
        component={CompletePinyinToneLesson}
        durationInFrames={completePinyinToneLessonDuration}
        defaultProps={completePinyinToneLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteTenOnesMakeOneTenLesson"
        component={CompleteTenOnesMakeOneTenLesson}
        durationInFrames={completeTenOnesMakeOneTenLessonDuration}
        defaultProps={completeTenOnesMakeOneTenLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteKp1FenYuHeIntroLesson"
        component={CompleteKp1FenYuHeIntroLesson}
        durationInFrames={completeKp1FenYuHeIntroLessonDuration}
        defaultProps={completeKp1FenYuHeIntroLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteKp2CountingByTensLesson"
        component={CompleteKp2CountingByTensLesson}
        durationInFrames={completeKp2CountingByTensLessonDuration}
        defaultProps={completeKp2CountingByTensLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteKp2v2CountingByTensLesson"
        component={CompleteKp2v2CountingByTensLesson}
        durationInFrames={completeKp2v2CountingByTensLessonDuration}
        defaultProps={completeKp2v2CountingByTensLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckTenOnesMakeOneTenBundleWrap"
        component={PrimitiveCheckTenOnesMakeOneTenBundleWrap}
        durationInFrames={primitiveCheckTenOnesMakeOneTenDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckTenOnesMakeOneTenStickRow"
        component={PrimitiveCheckTenOnesMakeOneTenStickRow}
        durationInFrames={primitiveCheckTenOnesMakeOneTenDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckKp1FenHeDiagramHardest"
        component={PrimitiveCheckKp1FenHeDiagramHardest}
        durationInFrames={primitiveCheckKp1FenHeDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckKp1FenHeDiagramMultiplicity"
        component={PrimitiveCheckKp1FenHeDiagramMultiplicity}
        durationInFrames={primitiveCheckKp1FenHeDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckKp1FenHeDiagramMigration"
        component={PrimitiveCheckKp1FenHeDiagramMigration}
        durationInFrames={primitiveCheckKp1FenHeDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PinyinToneLesson"
        component={PinyinToneLesson}
        durationInFrames={educationSceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="HanziMatchLesson"
        component={HanziMatchLesson}
        durationInFrames={educationSceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="InkWashDemo"
        component={InkWashDemo}
        durationInFrames={90}
        {...compositionDefaults}
      />
      <Composition
        id="AssetMorphDemo"
        component={AssetMorphDemo}
        durationInFrames={ASSET_MORPH_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="GlyphStrokeWriterHardest"
        component={GlyphStrokeWriterHardest}
        durationInFrames={GLYPH_HARDEST_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="GlyphStrokeWriterMultiplicity"
        component={GlyphStrokeWriterMultiplicity}
        durationInFrames={GLYPH_MULTIPLICITY_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="GlyphStrokeWriterSymbols"
        component={GlyphStrokeWriterSymbols}
        durationInFrames={GLYPH_SYMBOLS_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="OrderedRowSpotlightSplit"
        component={OrderedRowSpotlightSplit}
        durationInFrames={ORDERED_ROW_SPOTLIGHT_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="OrderedRowSpotlightMultiplicity"
        component={OrderedRowSpotlightMultiplicity}
        durationInFrames={ORDERED_ROW_SPOTLIGHT_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="OrderedRowSpotlightFlip"
        component={OrderedRowSpotlightFlip}
        durationInFrames={ORDERED_ROW_SPOTLIGHT_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="OrdinalLabelTokenHardest"
        component={OrdinalLabelTokenHardest}
        durationInFrames={ORDINAL_LABEL_TOKEN_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="OrdinalLabelTokenMultiplicity"
        component={OrdinalLabelTokenMultiplicity}
        durationInFrames={ORDINAL_LABEL_TOKEN_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="ComponentGallery"
        component={ComponentGallery}
        durationInFrames={componentGalleryDuration}
        fps={video.fps}
        height={COMPONENT_GALLERY_HEIGHT}
        width={COMPONENT_GALLERY_WIDTH}
      />
    </>
  );
};
