import "./index.css";
import { Composition } from "remotion";
import {
  ComponentGallery,
  COMPONENT_GALLERY_HEIGHT,
  COMPONENT_GALLERY_WIDTH,
  componentGalleryDuration,
} from "./component-gallery/ComponentGallery";
import {
  AssetGallery,
  ASSET_GALLERY_HEIGHT,
  ASSET_GALLERY_WIDTH,
  assetGalleryDuration,
} from "./scenes/AssetGallery";
import {
  ABSTRACTION_LADDER_DEMO_DURATION,
  AbstractionLadderColumn,
  AbstractionLadderRow,
} from "./scenes/AbstractionLadderDemo";
import {
  COUNTING_BEAD_HARDEST_DURATION,
  COUNTING_BEAD_MULTIPLICITY_DURATION,
  CountingBeadDeviceHardest,
  CountingBeadDeviceMultiplicity,
} from "./scenes/CountingBeadDeviceDemo";
import { InkWashDemo } from "./scenes/InkWashDemo";
import {
  AssetMorphDemo,
  ASSET_MORPH_DEMO_DURATION,
} from "./scenes/AssetMorphDemo";
import {
  DIALOGUE_EXCHANGE_DEMO_DURATION,
  DialogueExchangeChinese,
  DialogueExchangeHardest,
  DialogueExchangeMultiplicity,
} from "./scenes/DialogueExchangeDemo";
import {
  VOCAB_FLASHCARD_DEMO_DURATION,
  VocabFlashcardChinese,
  VocabFlashcardFlip,
  VocabFlashcardHardest,
  VocabFlashcardMultiplicity,
} from "./scenes/VocabFlashcardDemo";
import {
  MATCH_PAIRS_BOARD_DEMO_DURATION,
  MatchPairsBoardChinese,
  MatchPairsBoardEnglish,
  MatchPairsBoardHardest,
  MatchPairsBoardMultiplicity,
} from "./scenes/MatchPairsBoardDemo";
import {
  READ_ALONG_HIGHLIGHT_DEMO_DURATION,
  ReadAlongHighlightChinese,
  ReadAlongHighlightEnglish,
  ReadAlongHighlightHardest,
  ReadAlongHighlightMultiplicity,
} from "./scenes/ReadAlongHighlightDemo";
import {
  GLYPH_HARDEST_DURATION,
  GLYPH_MULTIPLICITY_DURATION,
  GLYPH_SYMBOLS_DURATION,
  GlyphStrokeWriterHardest,
  GlyphStrokeWriterMultiplicity,
  GlyphStrokeWriterSymbols,
} from "./scenes/GlyphStrokeWriterDemo";
import {
  GLYPH_DATA_BASICS_DURATION,
  GLYPH_DATA_CHARS_DURATION,
  GLYPH_DATA_HARDEST_DURATION,
  GlyphStrokeDataBasics,
  GlyphStrokeDataCharacters,
  GlyphStrokeDataHardest,
} from "./scenes/GlyphStrokeDataDemo";
import {
  ORDERED_ROW_SPOTLIGHT_DEMO_DURATION,
  OrderedRowSpotlightFlip,
  OrderedRowSpotlightMultiplicity,
  OrderedRowSpotlightSplit,
} from "./scenes/OrderedRowSpotlightDemo";
import {
  PART_WHOLE_COMPOSER_DEMO_DURATION,
  PartWholeComposerHardest,
  PartWholeComposerMerge,
  PartWholeComposerMultiplicity,
  PartWholeComposerSplit,
} from "./scenes/PartWholeComposerDemo";
import {
  PICTOGRAPH_EVOLUTION_DEMO_DURATION,
  PictographEvolutionHardest,
  PictographEvolutionMountain,
  PictographEvolutionSunOverlap,
  PictographEvolutionWaterCrossfade,
} from "./scenes/PictographEvolutionDemo";
import {
  ORDINAL_LABEL_TOKEN_DEMO_DURATION,
  OrdinalLabelTokenHardest,
  OrdinalLabelTokenMultiplicity,
} from "./scenes/OrdinalLabelTokenDemo";
import {
  CountingDemo,
  CompleteComparisonLesson,
  CompleteFenYuHeLesson,
  CompleteKp1FenYuHeIntroLesson,
  CompleteKp1HelloGreetingsLesson,
  CompleteKp2CountingByTensLesson,
  CompleteMakeTenLesson,
  CompletePinyinToneLesson,
  CompleteTenOnesMakeOneTenLesson,
  EducationShapeShowcase,
  FishCountingLesson,
  HanziMatchLesson,
  HybridSketchMotionDemo,
  MyComposition,
  OneToOneCompareLesson,
  PathFollowDemo,
  PinyinToneLesson,
  PrimitiveCheckKp1FenHeDiagramHardest,
  PrimitiveCheckKp1FenHeDiagramMigration,
  PrimitiveCheckKp1FenHeDiagramMultiplicity,
  PrimitiveCheckKp1HelloGreetingsHardest,
  PrimitiveCheckKp1HelloGreetingsMultiplicity,
  PrimitiveCheckTenOnesMakeOneTenBundleWrap,
  PrimitiveCheckTenOnesMakeOneTenStickRow,
  ShapePrimitiveGallery,
  StrokeTraceDemo,
  primitiveCheckKp1FenHeDuration,
  primitiveCheckKp1HelloDuration,
  primitiveCheckTenOnesMakeOneTenDuration,
  completeComparisonLessonDefaultProps,
  completeComparisonLessonDuration,
  completeFenYuHeLessonDefaultProps,
  completeFenYuHeLessonDuration,
  completeKp1FenYuHeIntroLessonDefaultProps,
  completeKp1FenYuHeIntroLessonDuration,
  completeKp1HelloGreetingsLessonDefaultProps,
  completeKp1HelloGreetingsLessonDuration,
  completeKp2CountingByTensLessonDefaultProps,
  completeKp2CountingByTensLessonDuration,
  completeMakeTenLessonDefaultProps,
  completeMakeTenLessonDuration,
  completePinyinToneLessonDefaultProps,
  completePinyinToneLessonDuration,
  completeTenOnesMakeOneTenLessonDefaultProps,
  completeTenOnesMakeOneTenLessonDuration,
  educationSceneDuration,
  educationShowcaseDuration,
  hybridSketchMotionDuration,
} from "./Composition";
import { video } from "./theme";
import { AUTO_LESSON_COMPOSITIONS } from "./lessons/_lessonRegistry.generated";

const compositionDefaults = {
  fps: video.fps,
  height: video.height,
  width: video.width,
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="SvgPrimitiveShowcase"
        component={MyComposition}
        durationInFrames={video.showcaseDuration}
        {...compositionDefaults}
      />
      <Composition
        id="CountingDemo"
        component={CountingDemo}
        durationInFrames={video.sceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PathFollowDemo"
        component={PathFollowDemo}
        durationInFrames={video.sceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="AbstractionLadderRow"
        component={AbstractionLadderRow}
        durationInFrames={ABSTRACTION_LADDER_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="AbstractionLadderColumn"
        component={AbstractionLadderColumn}
        durationInFrames={ABSTRACTION_LADDER_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="CountingBeadDeviceHardest"
        component={CountingBeadDeviceHardest}
        durationInFrames={COUNTING_BEAD_HARDEST_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="CountingBeadDeviceMultiplicity"
        component={CountingBeadDeviceMultiplicity}
        durationInFrames={COUNTING_BEAD_MULTIPLICITY_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="StrokeTraceDemo"
        component={StrokeTraceDemo}
        durationInFrames={video.sceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="HybridSketchMotionDemo"
        component={HybridSketchMotionDemo}
        durationInFrames={hybridSketchMotionDuration}
        {...compositionDefaults}
      />
      <Composition
        id="EducationShapeShowcase"
        component={EducationShapeShowcase}
        durationInFrames={educationShowcaseDuration}
        {...compositionDefaults}
      />
      <Composition
        id="ShapePrimitiveGallery"
        component={ShapePrimitiveGallery}
        durationInFrames={educationSceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="FishCountingLesson"
        component={FishCountingLesson}
        durationInFrames={educationSceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="OneToOneCompareLesson"
        component={OneToOneCompareLesson}
        durationInFrames={educationSceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteComparisonLesson"
        component={CompleteComparisonLesson}
        durationInFrames={completeComparisonLessonDuration}
        defaultProps={completeComparisonLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteFenYuHeLesson"
        component={CompleteFenYuHeLesson}
        durationInFrames={completeFenYuHeLessonDuration}
        defaultProps={completeFenYuHeLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteMakeTenLesson"
        component={CompleteMakeTenLesson}
        durationInFrames={completeMakeTenLessonDuration}
        defaultProps={completeMakeTenLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompletePinyinToneLesson"
        component={CompletePinyinToneLesson}
        durationInFrames={completePinyinToneLessonDuration}
        defaultProps={completePinyinToneLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteTenOnesMakeOneTenLesson"
        component={CompleteTenOnesMakeOneTenLesson}
        durationInFrames={completeTenOnesMakeOneTenLessonDuration}
        defaultProps={completeTenOnesMakeOneTenLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteKp1FenYuHeIntroLesson"
        component={CompleteKp1FenYuHeIntroLesson}
        durationInFrames={completeKp1FenYuHeIntroLessonDuration}
        defaultProps={completeKp1FenYuHeIntroLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteKp1HelloGreetingsLesson"
        component={CompleteKp1HelloGreetingsLesson}
        durationInFrames={completeKp1HelloGreetingsLessonDuration}
        defaultProps={completeKp1HelloGreetingsLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="CompleteKp2CountingByTensLesson"
        component={CompleteKp2CountingByTensLesson}
        durationInFrames={completeKp2CountingByTensLessonDuration}
        defaultProps={completeKp2CountingByTensLessonDefaultProps}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckTenOnesMakeOneTenBundleWrap"
        component={PrimitiveCheckTenOnesMakeOneTenBundleWrap}
        durationInFrames={primitiveCheckTenOnesMakeOneTenDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckTenOnesMakeOneTenStickRow"
        component={PrimitiveCheckTenOnesMakeOneTenStickRow}
        durationInFrames={primitiveCheckTenOnesMakeOneTenDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckKp1FenHeDiagramHardest"
        component={PrimitiveCheckKp1FenHeDiagramHardest}
        durationInFrames={primitiveCheckKp1FenHeDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckKp1FenHeDiagramMultiplicity"
        component={PrimitiveCheckKp1FenHeDiagramMultiplicity}
        durationInFrames={primitiveCheckKp1FenHeDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckKp1FenHeDiagramMigration"
        component={PrimitiveCheckKp1FenHeDiagramMigration}
        durationInFrames={primitiveCheckKp1FenHeDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckKp1HelloGreetingsHardest"
        component={PrimitiveCheckKp1HelloGreetingsHardest}
        durationInFrames={primitiveCheckKp1HelloDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PrimitiveCheckKp1HelloGreetingsMultiplicity"
        component={PrimitiveCheckKp1HelloGreetingsMultiplicity}
        durationInFrames={primitiveCheckKp1HelloDuration}
        {...compositionDefaults}
      />
      <Composition
        id="PinyinToneLesson"
        component={PinyinToneLesson}
        durationInFrames={educationSceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="HanziMatchLesson"
        component={HanziMatchLesson}
        durationInFrames={educationSceneDuration}
        {...compositionDefaults}
      />
      <Composition
        id="InkWashDemo"
        component={InkWashDemo}
        durationInFrames={90}
        {...compositionDefaults}
      />
      <Composition
        id="AssetMorphDemo"
        component={AssetMorphDemo}
        durationInFrames={ASSET_MORPH_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="DialogueExchangeHardest"
        component={DialogueExchangeHardest}
        durationInFrames={DIALOGUE_EXCHANGE_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="DialogueExchangeMultiplicity"
        component={DialogueExchangeMultiplicity}
        durationInFrames={DIALOGUE_EXCHANGE_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="DialogueExchangeChinese"
        component={DialogueExchangeChinese}
        durationInFrames={DIALOGUE_EXCHANGE_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="VocabFlashcardHardest"
        component={VocabFlashcardHardest}
        durationInFrames={VOCAB_FLASHCARD_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="VocabFlashcardFlip"
        component={VocabFlashcardFlip}
        durationInFrames={VOCAB_FLASHCARD_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="VocabFlashcardMultiplicity"
        component={VocabFlashcardMultiplicity}
        durationInFrames={VOCAB_FLASHCARD_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="VocabFlashcardChinese"
        component={VocabFlashcardChinese}
        durationInFrames={VOCAB_FLASHCARD_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="MatchPairsBoardHardest"
        component={MatchPairsBoardHardest}
        durationInFrames={MATCH_PAIRS_BOARD_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="MatchPairsBoardMultiplicity"
        component={MatchPairsBoardMultiplicity}
        durationInFrames={MATCH_PAIRS_BOARD_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="MatchPairsBoardChinese"
        component={MatchPairsBoardChinese}
        durationInFrames={MATCH_PAIRS_BOARD_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="MatchPairsBoardEnglish"
        component={MatchPairsBoardEnglish}
        durationInFrames={MATCH_PAIRS_BOARD_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="ReadAlongHighlightHardest"
        component={ReadAlongHighlightHardest}
        durationInFrames={READ_ALONG_HIGHLIGHT_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="ReadAlongHighlightMultiplicity"
        component={ReadAlongHighlightMultiplicity}
        durationInFrames={READ_ALONG_HIGHLIGHT_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="ReadAlongHighlightChinese"
        component={ReadAlongHighlightChinese}
        durationInFrames={READ_ALONG_HIGHLIGHT_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="ReadAlongHighlightEnglish"
        component={ReadAlongHighlightEnglish}
        durationInFrames={READ_ALONG_HIGHLIGHT_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="GlyphStrokeWriterHardest"
        component={GlyphStrokeWriterHardest}
        durationInFrames={GLYPH_HARDEST_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="GlyphStrokeWriterMultiplicity"
        component={GlyphStrokeWriterMultiplicity}
        durationInFrames={GLYPH_MULTIPLICITY_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="GlyphStrokeWriterSymbols"
        component={GlyphStrokeWriterSymbols}
        durationInFrames={GLYPH_SYMBOLS_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="GlyphStrokeDataCharacters"
        component={GlyphStrokeDataCharacters}
        durationInFrames={GLYPH_DATA_CHARS_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="GlyphStrokeDataBasics"
        component={GlyphStrokeDataBasics}
        durationInFrames={GLYPH_DATA_BASICS_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="GlyphStrokeDataHardest"
        component={GlyphStrokeDataHardest}
        durationInFrames={GLYPH_DATA_HARDEST_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="OrderedRowSpotlightSplit"
        component={OrderedRowSpotlightSplit}
        durationInFrames={ORDERED_ROW_SPOTLIGHT_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="OrderedRowSpotlightMultiplicity"
        component={OrderedRowSpotlightMultiplicity}
        durationInFrames={ORDERED_ROW_SPOTLIGHT_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="OrderedRowSpotlightFlip"
        component={OrderedRowSpotlightFlip}
        durationInFrames={ORDERED_ROW_SPOTLIGHT_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="PartWholeComposerHardest"
        component={PartWholeComposerHardest}
        durationInFrames={PART_WHOLE_COMPOSER_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="PartWholeComposerMultiplicity"
        component={PartWholeComposerMultiplicity}
        durationInFrames={PART_WHOLE_COMPOSER_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="PartWholeComposerMerge"
        component={PartWholeComposerMerge}
        durationInFrames={PART_WHOLE_COMPOSER_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="PartWholeComposerSplit"
        component={PartWholeComposerSplit}
        durationInFrames={PART_WHOLE_COMPOSER_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="PictographEvolutionHardest"
        component={PictographEvolutionHardest}
        durationInFrames={PICTOGRAPH_EVOLUTION_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="PictographEvolutionSunOverlap"
        component={PictographEvolutionSunOverlap}
        durationInFrames={PICTOGRAPH_EVOLUTION_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="PictographEvolutionMountain"
        component={PictographEvolutionMountain}
        durationInFrames={PICTOGRAPH_EVOLUTION_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="PictographEvolutionWaterCrossfade"
        component={PictographEvolutionWaterCrossfade}
        durationInFrames={PICTOGRAPH_EVOLUTION_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="OrdinalLabelTokenHardest"
        component={OrdinalLabelTokenHardest}
        durationInFrames={ORDINAL_LABEL_TOKEN_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="OrdinalLabelTokenMultiplicity"
        component={OrdinalLabelTokenMultiplicity}
        durationInFrames={ORDINAL_LABEL_TOKEN_DEMO_DURATION}
        {...compositionDefaults}
      />
      <Composition
        id="ComponentGallery"
        component={ComponentGallery}
        durationInFrames={componentGalleryDuration}
        fps={video.fps}
        height={COMPONENT_GALLERY_HEIGHT}
        width={COMPONENT_GALLERY_WIDTH}
      />
      <Composition
        id="AssetGallery"
        component={AssetGallery}
        durationInFrames={assetGalleryDuration}
        fps={video.fps}
        height={ASSET_GALLERY_HEIGHT}
        width={ASSET_GALLERY_WIDTH}
      />
      {/*
        AUTO-DISCOVERED LESSONS — every src/lessons/Complete*Lesson.tsx that exports a
        `lessonComposition` descriptor (discovered by `npm run lessons:registry`). The Wave-4
        composer registers a lesson by exporting that descriptor from its OWN file — it never
        hand-edits this list, so parallel worktree runs never collide here. A lesson is EITHER
        hand-registered above OR auto-discovered here, never both (Remotion throws on a duplicate id).
      */}
      {AUTO_LESSON_COMPOSITIONS.map((c) => (
        <Composition
          key={c.id}
          id={c.id}
          component={c.component}
          durationInFrames={c.durationInFrames}
          defaultProps={c.defaultProps}
          fps={c.fps ?? compositionDefaults.fps}
          height={c.height ?? compositionDefaults.height}
          width={c.width ?? compositionDefaults.width}
        />
      ))}
    </>
  );
};
